"""Add unique constraint to user_id and date in mood_logs

Revision ID: 63e330b75d2f
Revises: 8854320d7882
Create Date: 2025-05-21 01:22:53.736929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63e330b75d2f'
down_revision = '8854320d7882'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.create_unique_constraint('uix_user_date', ['user_id', 'date'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.drop_constraint('uix_user_date', type_='unique')

    # ### end Alembic commands ###
