"""enable mood null

Revision ID: 8854320d7882
Revises: ff3d99d295c0
Create Date: 2025-05-21 01:09:34.258047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8854320d7882'
down_revision = 'ff3d99d295c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.alter_column('mood',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.alter_column('mood',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    # ### end Alembic commands ###
