"""add diary

Revision ID: ff3d99d295c0
Revises: 3109e2527d6a
Create Date: 2025-05-21 01:05:37.766735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff3d99d295c0'
down_revision = '3109e2527d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('diary', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.drop_column('diary')

    # ### end Alembic commands ###
